/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVouchersRouteImport } from './routes/_app/vouchers'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppStaffRouteImport } from './routes/_app/staff'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReviewsRouteImport } from './routes/_app/reviews'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppMessagingRouteImport } from './routes/_app/messaging'
import { Route as AppMarketplaceRouteImport } from './routes/_app/marketplace'
import { Route as AppLogsRouteImport } from './routes/_app/logs'
import { Route as AppLocationsRouteImport } from './routes/_app/locations'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppGiftCardsRouteImport } from './routes/_app/gift-cards'
import { Route as AppDiscountsRouteImport } from './routes/_app/discounts'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppBlogsRouteImport } from './routes/_app/blogs'
import { Route as AppBannersRouteImport } from './routes/_app/banners'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products.index'
import { Route as AppProductsBulkUploadRouteImport } from './routes/_app/products.bulk-upload'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVouchersRoute = AppVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffRoute = AppStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagingRoute = AppMessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppGiftCardsRoute = AppGiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscountsRoute = AppDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppBlogsRoute = AppBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AppRoute,
} as any)
const AppBannersRoute = AppBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsBulkUploadRoute = AppProductsBulkUploadRouteImport.update({
  id: '/bulk-upload',
  path: '/bulk-upload',
  getParentRoute: () => AppProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/analytics': typeof AppAnalyticsRoute
  '/banners': typeof AppBannersRoute
  '/blogs': typeof AppBlogsRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/discounts': typeof AppDiscountsRoute
  '/gift-cards': typeof AppGiftCardsRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/logs': typeof AppLogsRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/messaging': typeof AppMessagingRoute
  '/orders': typeof AppOrdersRoute
  '/products': typeof AppProductsRouteWithChildren
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/transactions': typeof AppTransactionsRoute
  '/vouchers': typeof AppVouchersRoute
  '/products/bulk-upload': typeof AppProductsBulkUploadRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/analytics': typeof AppAnalyticsRoute
  '/banners': typeof AppBannersRoute
  '/blogs': typeof AppBlogsRoute
  '/categories': typeof AppCategoriesRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/discounts': typeof AppDiscountsRoute
  '/gift-cards': typeof AppGiftCardsRoute
  '/inventory': typeof AppInventoryRoute
  '/locations': typeof AppLocationsRoute
  '/logs': typeof AppLogsRoute
  '/marketplace': typeof AppMarketplaceRoute
  '/messaging': typeof AppMessagingRoute
  '/orders': typeof AppOrdersRoute
  '/reviews': typeof AppReviewsRoute
  '/settings': typeof AppSettingsRoute
  '/staff': typeof AppStaffRoute
  '/transactions': typeof AppTransactionsRoute
  '/vouchers': typeof AppVouchersRoute
  '/products/bulk-upload': typeof AppProductsBulkUploadRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/banners': typeof AppBannersRoute
  '/_app/blogs': typeof AppBlogsRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/discounts': typeof AppDiscountsRoute
  '/_app/gift-cards': typeof AppGiftCardsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/locations': typeof AppLocationsRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/marketplace': typeof AppMarketplaceRoute
  '/_app/messaging': typeof AppMessagingRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/products': typeof AppProductsRouteWithChildren
  '/_app/reviews': typeof AppReviewsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/staff': typeof AppStaffRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/vouchers': typeof AppVouchersRoute
  '/_app/products/bulk-upload': typeof AppProductsBulkUploadRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/verify-email'
    | '/analytics'
    | '/banners'
    | '/blogs'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/discounts'
    | '/gift-cards'
    | '/inventory'
    | '/locations'
    | '/logs'
    | '/marketplace'
    | '/messaging'
    | '/orders'
    | '/products'
    | '/reviews'
    | '/settings'
    | '/staff'
    | '/transactions'
    | '/vouchers'
    | '/products/bulk-upload'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/verify-email'
    | '/analytics'
    | '/banners'
    | '/blogs'
    | '/categories'
    | '/customers'
    | '/dashboard'
    | '/discounts'
    | '/gift-cards'
    | '/inventory'
    | '/locations'
    | '/logs'
    | '/marketplace'
    | '/messaging'
    | '/orders'
    | '/reviews'
    | '/settings'
    | '/staff'
    | '/transactions'
    | '/vouchers'
    | '/products/bulk-upload'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/accept-invite'
    | '/login'
    | '/reset-password'
    | '/set-password'
    | '/signup'
    | '/verify-email'
    | '/_app/analytics'
    | '/_app/banners'
    | '/_app/blogs'
    | '/_app/categories'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/discounts'
    | '/_app/gift-cards'
    | '/_app/inventory'
    | '/_app/locations'
    | '/_app/logs'
    | '/_app/marketplace'
    | '/_app/messaging'
    | '/_app/orders'
    | '/_app/products'
    | '/_app/reviews'
    | '/_app/settings'
    | '/_app/staff'
    | '/_app/transactions'
    | '/_app/vouchers'
    | '/_app/products/bulk-upload'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vouchers': {
      id: '/_app/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AppVouchersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff': {
      id: '/_app/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AppStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reviews': {
      id: '/_app/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messaging': {
      id: '/_app/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof AppMessagingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketplace': {
      id: '/_app/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locations': {
      id: '/_app/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gift-cards': {
      id: '/_app/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof AppGiftCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discounts': {
      id: '/_app/discounts'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AppDiscountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/blogs': {
      id: '/_app/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof AppBlogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banners': {
      id: '/_app/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof AppBannersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/bulk-upload': {
      id: '/_app/products/bulk-upload'
      path: '/bulk-upload'
      fullPath: '/products/bulk-upload'
      preLoaderRoute: typeof AppProductsBulkUploadRouteImport
      parentRoute: typeof AppProductsRoute
    }
  }
}

interface AppProductsRouteChildren {
  AppProductsBulkUploadRoute: typeof AppProductsBulkUploadRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsBulkUploadRoute: AppProductsBulkUploadRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBannersRoute: typeof AppBannersRoute
  AppBlogsRoute: typeof AppBlogsRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDiscountsRoute: typeof AppDiscountsRoute
  AppGiftCardsRoute: typeof AppGiftCardsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMessagingRoute: typeof AppMessagingRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppReviewsRoute: typeof AppReviewsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStaffRoute: typeof AppStaffRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppVouchersRoute: typeof AppVouchersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBannersRoute: AppBannersRoute,
  AppBlogsRoute: AppBlogsRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDiscountsRoute: AppDiscountsRoute,
  AppGiftCardsRoute: AppGiftCardsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppLogsRoute: AppLogsRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMessagingRoute: AppMessagingRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppReviewsRoute: AppReviewsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStaffRoute: AppStaffRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppVouchersRoute: AppVouchersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
